### ISSUE TITLE
change event is not triggered

### ISSUE THREAD

**Issue by Eijun** [rennzhang/codemirror-editor-vue3#41]
### Describe the bug

When I delete the value entirely at the first load of editor, the change event is not triggered.

version: 2.1.4

### step
1. select all code text in editor use command + A
2. push "delete" button

In addition, the event is not triggered, so the connected model value is not changed.

### Validations

- [X] Read the [docs](https://renncheung.github.io/codemirror-editor-vue3/en/guide/getting-started).
- [X] Check that there isn't [already an issue](https://github.com/RennCheung/codemirror-editor-vue3/issues?q=) that reports the same bug to avoid creating a duplicate.

**Comment by rennzhang** [comment]
Sorry, I can't come up with the problem you said.

Please update to the latest version to try again or provide a minimal reproducible example

**Comment by Eijun** [comment]
I checked that the problem disappeared after upgrading to the latest version.

Thank you for your help! 👍
