### ISSUE TITLE
2.3.1 is broken

### ISSUE THREAD

**Issue by Tofandel** [rennzhang/codemirror-editor-vue3#42]
### Describe the bug

Seems the 2.3.1 publication is broken

When building with it, I get the error
`contains a reference to the file "codemirror-editor-vue3". This file can not be found, please check it for typos or update it if the file got moved.`

### Validations

- [X] Read the [docs](https://rennzhang.github.io/codemirror-editor-vue3/guide/getting-started).
- [X] Check that there isn't [already an issue](https://github.com/RennCheung/codemirror-editor-vue3/issues?q=) that reports the same bug to avoid creating a duplicate.

**Comment by Ximeng0918** [comment]
I also encountered this problem. The dist directory of this version on npm is empty. I guess the author forgot the project packaging when publishing, so I returned 2.3.0 to use

**Comment by Tofandel** [comment]
@rennzhang 
Consider adding a `"prepublishOnly": "npm run build",` script in the `package.json` to avoid this issue in the future

**Comment by rennzhang** [comment]
I am very sorry for this low-level problem, which has been fixed.

> For version 2.4.0, only README.md and some code formatting have been updated, and no other code has been updated, please feel free to use (or continue to use 2.3.0)

**Comment by rennzhang** [comment]
> @rennzhang 考虑在中添加`"prepublishOnly": "npm run build",`脚本以`package.json`避免将来出现此问题

Thank you very much for your suggestion, I have added this command to package.json
