### ISSUE TITLE
如何对输入的代码进行校验

### ISSUE THREAD

**Issue by leipu247** [rennzhang/codemirror-editor-vue3#45]
因为在编辑器我要输入vue代码供前台加载渲染，所以想在输入时校验这段vue代码的准确性，请问下如何实现

**Comment by rennzhang** [comment]
codemirror 我暂时没找到校验 vue 的包，可以看下 monaco

参考：https://play.vuejs.org/#eNp9kUFLwzAUx7/KM5cqzBXR0+gGKgP1oKKCl1xG99ZlpklIXuag9Lv7krK5w9it7//7v/SXthP3zo23EcVEVKH2yhEEpOhm0qjWWU/QgccV9LDytoWCq4U00tTWBII2NDBN/LJ4Qq0tfFuvlxfFlTRVORzHB/FA2Dq9IOQJoFrfzLouL/d9VfKUU2VcJNhet3aJeioFcymgZFiVR/tiJCjw61eqGW+CNWzepX0pats6pdG/OVKsJ8UEMklswXa/LzkjH3G0z+s11j8n8k3YpUyKd48B/RalODBa+AZpwPPPV9zx8wGyfdTcPgM/MFgdk+NQe4hmydpHvWz7nL+/Ms1XmO8ITdhfKommZp/7UvA/eTxz9X/d2/Fd3pOmF/0fEx+nNQ==
