### ISSUE TITLE
怎么让它支持json语法高亮

### ISSUE THREAD

**Issue by ilysusu** [rennzhang/codemirror-editor-vue3#46]
![Uploading image.png…]()

**Comment by ilysusu** [comment]
const editorOptions = ref({
  mode: 'application/json', 
  theme: 'default',
  lineNumbers: true,
  lineWrapping: true,
});  设置mode 没有效果

**Comment by rennzhang** [comment]
配合最新版 codemirror5 似乎有些bug，有空我修复一下，如果着急就先用别的替代品吧

**Comment by rennzhang** [comment]
已解决，参考 https://rennzhang.github.io/codemirror-editor-vue3/example/codeLint
