### ISSUE TITLE
需要修复package.json文件中的exports字段

### ISSUE THREAD

**Issue by kaokei** [rennzhang/codemirror-editor-vue3#49]
### Describe the bug

目前的package.json的exports字段是有点问题的。
![image](https://github.com/rennzhang/codemirror-editor-vue3/assets/82272759/4b67745e-a3fd-4258-9f5a-14e33d1f3a46)

可以参考以下代码片段。
```
  "exports": {
    ".": {
      "import": {
        "types": "./dist/packages/index.d.ts",
        "default": "./dist/codemirror-editor-vue3.js"
      },
      "require": {
        "types": "./dist/packages/index.d.ts",
        "default": "./dist/codemirror-editor-vue3.umd.cjs"
      }
    }
  },
```

### Validations

- [X] Read the [docs](https://rennzhang.github.io/codemirror-editor-vue3/guide/getting-started).
- [X] Check that there isn't [already an issue](https://github.com/RennCheung/codemirror-editor-vue3/issues?q=) that reports the same bug to avoid creating a duplicate.

**Comment by rennzhang** [comment]
感谢指正，我会尽快修复这个问题

**Comment by rennzhang** [comment]
你好，请问您的typescript 以及其他依赖是什么版本呢？

目前我的环境未能复现，依赖版本如下：

```
    "typescript": "~5.4.3",
    "vue": "^3.4.21",
    "codemirror-editor-vue3": "^2.5.8",
    "codemirror": "^5",
    "vite": "^5.2.10",
```

**Comment by kaokei** [comment]
好像没看出来区别。那就先不管了吧，不影响开发。
