### ISSUE TITLE
需要更新 package 資訊

### ISSUE THREAD

**Issue by s1495k043** [rennzhang/codemirror-editor-vue3#51]
### Describe the bug

使用時出現
There are types at 'd:/projects/vue-project/node_modules/codemirror-editor-vue3/dist/packages/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'codemirror-editor-vue3' library may need to update its package.json or typings.
我想你需要在 package.json 加入
"exports": {
    ".": {
      "types": "./dist/packages/index.d.ts"
    },

### Validations

- [X] Read the [docs](https://rennzhang.github.io/codemirror-editor-vue3/guide/getting-started).
- [X] Check that there isn't [already an issue](https://github.com/RennCheung/codemirror-editor-vue3/issues?q=) that reports the same bug to avoid creating a duplicate.

**Comment by rennzhang** [comment]
感谢指出问题！

另外是否可以提供下您的 vue typescript vite vscode 版本呢

**Comment by rennzhang** [comment]
2.6.0 版本已增加相应内容

**Comment by rennzhang** [comment]
我自己在安装时也碰到类似的问题，但重启 TS 服务器后该问题消失了

<img width="1512" alt="image" src="https://github.com/rennzhang/codemirror-editor-vue3/assets/50518861/503d631a-7f5a-479d-a71c-516f2a2a5a08">
