### ISSUE TITLE
请求添加支持yaml高亮

### ISSUE THREAD

**Issue by yuzhid** [rennzhang/codemirror-editor-vue3#52]
请求添加支持yaml高亮

**Comment by rennzhang** [comment]
yaml 高亮是支持的，只是在文档示例中没有体现，现已增加示例：https://rennzhang.github.io/codemirror-editor-vue3/example/?lang=yaml

更多语言只需引入对应的语言包即可  https://rennzhang.github.io/codemirror-editor-vue3/zh-CN/guide/lang
