### ISSUE TITLE
style

### ISSUE THREAD

**Issue by Ari1c** [rennzhang/codemirror-editor-vue3#53]
### Describe the bug

切换tabs 或者展开百叶窗时，内部的codemirror 样式就变了，
![微信图片_20240613163123](https://github.com/rennzhang/codemirror-editor-vue3/assets/33024188/5d1aa9a9-96a3-4201-b83d-257c1d354948)

### Validations

- [X] Read the [docs](https://rennzhang.github.io/codemirror-editor-vue3/guide/getting-started).
- [X] Check that there isn't [already an issue](https://github.com/RennCheung/codemirror-editor-vue3/issues?q=) that reports the same bug to avoid creating a duplicate.

**Comment by rennzhang** [comment]
请问用的是哪个版本，我排查一下

**Comment by rennzhang** [comment]
> 设置的高度也不生效

升级到 最新版应该可以解决这个问题
