### ISSUE TITLE
jsonlint-mod 依赖导致了electron-builder运行错误

### ISSUE THREAD

**Issue by mhlsky** [rennzhang/codemirror-editor-vue3#60]
### Describe the bug

jsonlint-mod包含了一个死库，JSV。JSV内存在一个 pakage的dependencies属性写成了数组。
希望能够替换jsonlint-mod库，解决错误 传递。

### Steps to reproduce

![image](https://github.com/user-attachments/assets/8dd72cff-8834-4e89-a54c-a5af47179a68)

### Package Info

```shell
"version": "2.5.8",
```

### Validations

- [X] Is it the latest version?
- [X] Read the [docs](https://rennzhang.github.io/codemirror-editor-vue3/guide/getting-started).
- [X] Check that there isn't [already an issue](https://github.com/RennCheung/codemirror-editor-vue3/issues?q=) that reports the same bug to avoid creating a duplicate.
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by rennzhang** [comment]
能否帮忙提供一个最小可复现案例或复现步骤
我在 npm 找到另一个或许可用的库，他使用了 jsx-fixed，但需要实际测试
<img width="1455" alt="image" src="https://github.com/user-attachments/assets/3d77d537-018d-415c-84be-e95e7a0c096a">

**Comment by mhlsky** [comment]
https://github.com/mhlsky/errorDemo
我使用electron-vite 脚手架快速创建了一个demo。
下面是全部的执行创建命令：
npm create @quick-start/electron@latest
npm install codemirror-editor-vue3 codemirror@^5 -S
安装时不会报错。
再次执行 npm install即会触发electron-builder install-app-deps而导致错误。

**Comment by mhlsky** [comment]
我在github上回复不知你看到没有https://github.com/mhlsky/errorDemo




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月12日(星期四) 上午10:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rennzhang/codemirror-editor-vue3] jsonlint-mod 依赖导致了electron-builder运行错误 (Issue #60)














 
能否帮忙提供一个最小可复现案例或复现步骤
 我在 npm 找到另一个或许可用的库，他使用了 jsx-fixed，但需要实际测试
 image.png (view on web)

**Comment by rennzhang** [comment]
前两天比较忙，最新的 v2.8.0 版本解决了这个问题。

之前错误的把 `jsonlint-mod`包放到了 `dependencies`中，现在已经移除了。

经过测试在你的 demo 中可以自行安装使用jsonlint-mod这个包

**Comment by mhlsky** [comment]
这是来自QQ邮箱的自动回复邮件。已收----梦里飞Mhlsky(孟)
